[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "your_project_name"
version = "0.1.0"
description = "Your project description"
authors = [
    { name="Your Name", email="your.email@example.com" }
]
dependencies = [
    "numpy==2.0.4",
    "torch==2.1.6"
]

[project.urls]
Homepage = "https://example.com"
Repository = "https://github.com/example/your_project"