[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "iitp_spring"
version = "0.1.0"
description = "seminars"
authors = [
    { name="Elisey", email="ez1071@yandex.ru" }
]
dependencies = [
    "numpy==2.0.4",
    "torch==2.1.6"
]

[project.urls]
Homepage = "discord.ru"
Repository = "https://github.com/Elisey-e/IIPT_Python_25spring"